
const landing = document.getElementById("landing");
const dashboard = document.getElementById("dashboard");
const interview = document.getElementById("interview");
const report = document.getElementById("report");


const questionBox = document.getElementById("question");
const questionNumber = document.getElementById("questionNumber");
const timerElement = document.getElementById("timer");
const progressBar = document.getElementById("progressBar");
const answerBox = document.getElementById("answer");
const finalScore = document.getElementById("finalScore");


const questions = [
{
difficulty:"Easy",
question:"Tell me about yourself and your technical background."
},
{
difficulty:"Easy",
question:"What is the difference between HTML and CSS?"
},
{
difficulty:"Medium",
question:"Explain event bubbling in JavaScript."
},
{
difficulty:"Medium",
question:"What are React Hooks and why are they useful?"
},
{
difficulty:"Hard",
question:"How would you optimize a slow-loading website?"
}
];


let currentQuestion = 0;
let score = 0;
let timer = 60;
let timerInterval;


function openDashboard(){

landing.classList.add("hidden");
dashboard.classList.remove("hidden");

}


function startInterview() {

    const resumeInput =
    document.getElementById("resume");

    const jdInput =
    document.getElementById("jd");

    if (!resumeInput.files.length) {
        alert("Please upload your resume.");
        return;
    }

    if (jdInput.value.trim() === "") {
        alert("Please enter Job Description.");
        return;
    }

    document.getElementById("dashboard")
    .classList.add("hidden");

    document.getElementById("interview")
    .classList.remove("hidden");

    currentQuestion = 0;
    score = 0;

    loadQuestion();
    startTimer();
}


function loadQuestion(){

questionBox.innerText =
questions[currentQuestion].question;

questionNumber.innerText =
`Question ${currentQuestion + 1} / ${questions.length}`;

let progress =
(currentQuestion / questions.length) * 100;

progressBar.style.width =
progress + "%";

}


function startTimer(){

clearInterval(timerInterval);

timer = 60;

timerElement.innerText = timer;

timerInterval = setInterval(()=>{

timer--;

timerElement.innerText = timer;

if(timer <= 0){

submitAnswer();

}

},1000);

}


function submitAnswer(){

const answer =
answerBox.value.trim();

if(answer.length > 20){

score += 20;

}else if(answer.length > 5){

score += 10;

}

answerBox.value = "";

currentQuestion++;

if(currentQuestion < questions.length){

loadQuestion();
startTimer();

}else{

finishInterview();

}

}


function finishInterview(){

clearInterval(timerInterval);

interview.classList.add("hidden");
report.classList.remove("hidden");

let finalPercentage =
Math.min(score,100);

finalScore.innerText =
finalPercentage + "%";

generateFeedback(finalPercentage);

}


function generateFeedback(score){

let strengths =
document.createElement("div");

let weaknesses =
document.createElement("div");

if(score >= 80){

strengths.innerHTML = `
<h3>Strengths</h3>
<ul>
<li>Excellent Communication</li>
<li>Strong Technical Knowledge</li>
<li>Good Problem Solving</li>
</ul>
`;

weaknesses.innerHTML = `
<h3>Areas to Improve</h3>
<ul>
<li>Advanced System Design</li>
</ul>
`;

}
else if(score >= 50){

strengths.innerHTML = `
<h3>Strengths</h3>
<ul>
<li>Basic Technical Knowledge</li>
<li>Good Understanding of Concepts</li>
</ul>
`;

weaknesses.innerHTML = `
<h3>Areas to Improve</h3>
<ul>
<li>Communication Skills</li>
<li>Time Management</li>
<li>Problem Solving</li>
</ul>
`;

}
else{

strengths.innerHTML = `
<h3>Strengths</h3>
<ul>
<li>Willingness to Learn</li>
</ul>
`;

weaknesses.innerHTML = `
<h3>Areas to Improve</h3>
<ul>
<li>Technical Skills</li>
<li>Communication</li>
<li>Interview Confidence</li>
<li>Problem Solving</li>
</ul>
`;

}

document
.querySelector(".report-container")
.appendChild(strengths);

document
.querySelector(".report-container")
.appendChild(weaknesses);

}


function restartInterview(){

location.reload();

}


function downloadReport(){

let content = `
AI Interview Report

Final Score: ${score}%

Generated By:
AI Mock Interview Platform
`;

const blob =
new Blob([content],
{type:"text/plain"});

const link =
document.createElement("a");

link.href =
URL.createObjectURL(blob);

link.download =
"Interview_Report.txt";

link.click();

}